
#########################
### Sign up & Register ...
#########################

### Sign up
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "Michael",
  "password": "michael1234"
}


### Sign in
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "Michael",
  "password": "michael1234"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}



#######################
### Person ...
#######################

### Get all persons
GET http://localhost:8080/persons
Authorization: Bearer {{auth_token}}


### Get person by id
GET http://localhost:8080/persons/1
Authorization: Bearer {{auth_token}}


### Patch person by id
PATCH http://localhost:8080/persons/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "Michael2"
}


### Delete person by id
DELETE http://localhost:8080/persons/1
Authorization: Bearer {{auth_token}}

### Get all persons
GET http://localhost:8080/persons
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzIyODUwMzEsInN1YiI6InRlc3QifQ.7WJ-6DSuCUAsgTypd25Epi8YeL0k3ZyQQcrgDzZ_xts
